UNKNOWN_SPACE = 0
UNCLASSIFIED_OBJECT = 1
FREE_SPACE = 2
WALL = 3
CURRENT_CAR_POSITION = 9

GRANULARITY = 10
RELATIVE_MAP_WIDTH = 200 // GRANULARITY
RELTAIVE_MAP_HEIGHT = 100 // GRANULARITY

UP = 0
RIGHT = 1
DOWN = 2
LEFT = 3